name: Publish Beta Release to Github Only

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true

  workflow_call:
    inputs:
      branch:
        type: string
        required: true

jobs:
  save_artifacts:	
    if: ${{ github.event_name == 'workflow_dispatch' }}	
    name: 'Build VSIX Files'
    needs: get_release_variables
    runs-on: ubuntu-latest	

    steps:	
      - uses: actions/checkout@v3	
        with:	
          ref: ${{ github.event.inputs.branch }}	
      - uses: actions/setup-node@v3	
        with:
          node-version-file: '.nvmrc'	
      - run: npm install -g lerna	
      - run: npm install	
      - run: npm run compile	
      - run: npm run vscode:package	
      - name: Stage Artifacts	
        run: |	
          mkdir extensions	
          find packages -name "*.vsix" -type f -exec cp {} ./extensions \;	
          cp ./packages/salesforcedx-vscode/CHANGELOG.md ./extensions	
      - name: Upload Extensions	
        uses: actions/upload-artifact@v3	
        with:	
          name: ${{ needs.get_release_variables.outputs.RELEASE_VERSION }}
          path: ./extensions/	

  get_release_variables:
    # store the RELEASE_VERSION from the parent package as an output that we can reference elsewhere
    name: 'Get Release Environment Variables'
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.getVersion.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch || github.event.inputs.branch }}
      - id: getVersion
        run: echo "::set-output name=version::"$(node -pe "require('./packages/salesforcedx-vscode/package.json').version")""
      - run: echo "Release Version is ${{ steps.getVersion.outputs.version }}"

  create_git_tag:
    name: 'Create and Tag Beta Release'
    runs-on: ubuntu-latest
    needs: [get_release_variables, save_artifacts]
    if: ${{ needs.save_artifacts.result != 'skipped' || github.event_name == 'workflow_call' }}
    outputs:
      version: ${{ steps.version.outputs.version }}
      release_type: ${{ 'beta' }}
      result: ${{ steps.result.outputs.result }}
    env:
      VERSION: ${{ needs.get_release_variables.outputs.RELEASE_VERSION }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch || github.event.inputs.branch }}
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: ${{ needs.get_release_variables.outputs.RELEASE_VERSION }}
          path: tmp/saved-extensions
      - run: |
          cp ./packages/salesforcedx-vscode/CHANGELOG.md ./tmp/saved-extensions
      - uses: ./.github/actions/gitConfig
        with:
          email: ${{ secrets.IDEE_GH_EMAIL }}
      - name: 'Create git tag to map to the Release Version'
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}
      - name: 'Confirm all downloaded files'
        run: ls -R
        working-directory: tmp/saved-extensions
      - name: 'Create Pre-Release and Attach VSIX Files'
        run: gh release create v${{ env.VERSION }} **.vsix --title "Pre-Release v${{ env.VERSION }}" --notes-file CHANGELOG.md --prerelease
        working-directory: tmp/saved-extensions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: version
        run: echo "version=${{ env.VERSION }}" >> $GITHUB_OUTPUT

  slack_notification:
    if: ${{ always() }}
    needs: create_git_tag
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'Beta release v${{ needs.create_git_tag.outputs.version }}'
      failedEvent: 'Beta Release Publish'
      successfulEvent: '${{ github.event.repository.html_url }}/releases/${{ needs.create_git_tag.outputs.version }}'
      type: 'published'
      result: ${{ needs.create_git_tag.outputs.result }}
      workflow: 'publish-beta-release.yml'
